### ISSUE TITLE
Bug: Collector does not send logs to output endpoint

### ISSUE THREAD

**Issue by samuelarogbonlo** [kube-logging/telemetry-controller#157]
Great Project!!, i really like the idea here. Thank you to everyone involved. 

I think there an error in the collector config as logs are not sent to specified endpoint. i found the error while following this demo in the docs folder: [here](https://github.com/kube-logging/telemetry-controller/blob/main/docs/examples/simple-demo/one_tenant_two_subscriptions.yaml). 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: example-tenant-ns
  labels:
    nsSelector: example-tenant
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: example-collector
spec:
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: example-collector
  otelCommonFields:
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    volumeMounts:
      - name: varlogpods
        mountPath: /var/log/pods
        readOnly: true
    volumes:
      - name: varlogpods
        hostPath:
          path: /var/log/pods
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  name: example-tenant
  labels:
    collectorLabel: example-collector
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant
  logSourceNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-sample-1
  namespace: example-tenant-ns
spec:
  condition: "true"
  outputs:
    - name: otlp-test-output-1
      namespace: example-tenant-ns
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-sample-2
  namespace: example-tenant-ns
spec:
  condition: "true"
  outputs:
    - name: otlp-test-output-2
      namespace: example-tenant-ns
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: otlp-test-output-1
  namespace: example-tenant-ns
spec:
  otlp:
    endpoint: openobserve-otlp-grpc.openobserve.svc.cluster.local:5081
    headers:
      Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTp2RVRna3JPdFJnaTdQZzBG"
      organization: default
      stream-name: default
    tls:
      insecure: true
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: otlp-test-output-2
  namespace: example-tenant-ns
spec:
  otlp:
    endpoint: openobserve-otlp-grpc.openobserve.svc.cluster.local:5081
    headers:
      Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTp2RVRna3JPdFJnaTdQZzBG"
      organization: default
      stream-name: default
    tls:
      insecure: true

```

the log shows the collector is scraping the logs 

```logs
2025-03-28T00:15:09.969Z	info	service@v0.120.0/service.go:193	Setting up own telemetry...
2025-03-28T00:15:09.969Z	warn	service@v0.120.0/service.go:241	service::telemetry::metrics::address is being deprecated in favor of service::telemetry::metrics::readers
2025-03-28T00:15:09.971Z	info	memorylimiter@v0.120.0/memorylimiter.go:151	Using percentage memory limiter	{"otelcol.component.kind": "Processor", "total_memory_mib": 31800, "limit_percentage": 75, "spike_limit_percentage": 0}
2025-03-28T00:15:09.971Z	info	memorylimiter@v0.120.0/memorylimiter.go:75	Memory limiter configured	{"otelcol.component.kind": "Processor", "limit_mib": 23850, "spike_limit_mib": 4770, "check_interval": 1}
2025-03-28T00:15:09.973Z	info	service@v0.120.0/service.go:258	Starting axoflow-otel-collector...	{"Version": "0.120.0", "NumCPU": 16}
2025-03-28T00:15:09.973Z	info	extensions/extensions.go:40	Starting extensions...
2025-03-28T00:15:09.974Z	info	kube/client.go:141	k8s filtering	{"otelcol.component.id": "k8sattributes", "otelcol.component.kind": "Processor", "otelcol.pipeline.id": "logs/tenant_example-tenant", "otelcol.signal": "logs", "labelSelector": "", "fieldSelector": ""}
2025-03-28T00:15:09.975Z	info	adapter/receiver.go:41	Starting stanza receiver	{"otelcol.component.id": "filelog/example-tenant", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs"}
2025-03-28T00:15:09.976Z	info	service@v0.120.0/service.go:281	Everything is ready. Begin running and processing data.
2025-03-28T00:15:10.177Z	info	fileconsumer/file.go:265	Started watching file	{"otelcol.component.id": "filelog/example-tenant", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs", "component": "fileconsumer", "path": "/var/log/pods/example-tenant-ns_log-generator-1743120864-58995d7dd-dhhwd_6bc5b5e2-a827-440b-bfd2-f24567fbbbff/log-generator/0.log"}
2025-03-28T00:16:59.177Z	info	fileconsumer/file.go:265	Started watching file	{"otelcol.component.id": "filelog/example-tenant", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs", "component": "fileconsumer", "path": "/var/log/pods/example-tenant-ns_log-generator-1743121015-85777788bd-vzt54_2d93e9ea-b322-4bdf-854d-1c8c1e18fe1d/log-generator/0.log"}
```
but no telemetry is sent to open observe

<img width="1766" alt="Image" src="https://github.com/user-attachments/assets/6f3d6b9b-788c-46a2-bd84-128849807d1e" />
<img width="1790" alt="Image" src="https://github.com/user-attachments/assets/27c8d55c-7084-4bc3-bcfa-2278388c3aa9" />

faced the same error when trying the loki [demo](https://github.com/kube-logging/telemetry-controller/tree/main/docs/demos/loki). No logs were sent to loki

my open observe config

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openobserve
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: 5080
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve-otlp-grpc
  namespace: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
    - name: otlp-grpc
      port: 5081
      targetPort: 5081
---
# create statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    name: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      name: openobserve
      app: openobserve
  template:
    metadata:
      labels:
        name: openobserve
        app: openobserve
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      # terminationGracePeriodSeconds: 0
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:v0.14.0
          env:
            - name: ZO_ROOT_USER_EMAIL
              value: root@example.com
            - name: ZO_ROOT_USER_PASSWORD
              value: Complexpass#123
            - name: ZO_DATA_DIR
              value: /data
          # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 4096m
              memory: 2048Mi
            requests:
              cpu: 256m
              memory: 50Mi
          ports:
            - containerPort: 5080
              name: http
            - containerPort: 5081
              name: otlp-grpc
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        # storageClassName: default
        # NOTE: You can increase the storage size
        resources:
          requests:
            storage: 10Gi

```

**Comment by csatib02** [comment]
Hey @samuelarogbonlo,
First of all thanks for using the project!

I will look into this today, and come back with a solution!

**Comment by samuelarogbonlo** [comment]
> Hey [@samuelarogbonlo](https://github.com/samuelarogbonlo), First of all thanks for using the project!
> 
> I will look into this today and come back with a solution!

Okay, thanks,@csatib02. Also note that there were service & container port mismatches in the main code (I corrected it in this issue). Then even the operator itself is not in perfect shape.

**Comment by csatib02** [comment]
I've looked into this, the openobserve worked fine!
The Loki docs had a small misconfiguration in the example manifests, that's being fixed in: https://github.com/kube-logging/telemetry-controller/pull/158

**Comment by csatib02** [comment]
> Then even the operator itself is not in perfect shape.

The custom resources managed by this operator are heavily dependent on each other, resulting in a degree of eventual consistency between operations. This can result in failing reconciliation attempts, which the operator takes relatively lightly due to the underlying inter-dependencies.

**Comment by samuelarogbonlo** [comment]
@csatib02 thank you for the response. 

still can't getting to work with open observe. This is sample logs from the telementry controller 

```logs
2025-03-28T00:16:57Z	DEBUG	resource is in sync	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "55e9667f-30df-4aff-ab14-9e30349f01cc", "name": "example-collector-pod-association-reader", "apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRole"}
2025-03-28T00:16:57Z	DEBUG	resource is in sync	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "55e9667f-30df-4aff-ab14-9e30349f01cc", "name": "example-collector-sa", "namespace": "collector", "apiVersion": "v1", "kind": "ServiceAccount"}
2025-03-28T00:16:57Z	DEBUG	resource is in sync	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "55e9667f-30df-4aff-ab14-9e30349f01cc", "name": "example-collector-crb", "apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding"}
2025-03-28T00:16:57Z	DEBUG	could not match objects	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "55e9667f-30df-4aff-ab14-9e30349f01cc", "collector": "example-collector", "name": "otelcollector-example-collector", "namespace": "collector", "error": "Failed to generate strategic merge patch: unable to find api field in struct AnyConfig for the json field \"metrics\"", "errorVerbose": "unable to find api field in struct AnyConfig for the json field \"metrics\"\nFailed to generate strategic merge patch\ngithub.com/cisco-open/k8s-objectmatcher/patch.(*PatchMaker).Calculate\n\t/go/pkg/mod/github.com/cisco-open/k8s-objectmatcher@v1.10.0/patch/patch.go:87\ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.37.0/pkg/reconciler/resource.go:437\ngithub.com/kube-logging/telemetry-controller/controllers/telemetry.(*CollectorReconciler).Reconcile\n\t/usr/local/src/telemetry-controller/controllers/telemetry/collector_controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"}
2025-03-28T00:16:57Z	DEBUG	updating resource	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "55e9667f-30df-4aff-ab14-9e30349f01cc", "collector": "example-collector", "name": "otelcollector-example-collector", "namespace": "collector"}
2025-03-28T00:16:58Z	DEBUG	resource updated	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "55e9667f-30df-4aff-ab14-9e30349f01cc", "collector": "example-collector", "name": "otelcollector-example-collector", "namespace": "collector"}
2025-03-28T00:17:00Z	INFO	getting collector: "example-collector"	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "collector": "example-collector"}
2025-03-28T00:17:00Z	INFO	reconciling collector: "example-collector"	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "collector": "example-collector"}
2025-03-28T00:17:00Z	DEBUG	resource is in sync	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "name": "example-collector-pod-association-reader", "apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRole"}
2025-03-28T00:17:00Z	DEBUG	resource is in sync	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "name": "example-collector-sa", "namespace": "collector", "apiVersion": "v1", "kind": "ServiceAccount"}
2025-03-28T00:17:00Z	DEBUG	resource is in sync	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "name": "example-collector-crb", "apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding"}
2025-03-28T00:17:00Z	DEBUG	could not match objects	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "collector": "example-collector", "name": "otelcollector-example-collector", "namespace": "collector", "error": "Failed to generate strategic merge patch: unable to find api field in struct AnyConfig for the json field \"metrics\"", "errorVerbose": "unable to find api field in struct AnyConfig for the json field \"metrics\"\nFailed to generate strategic merge patch\ngithub.com/cisco-open/k8s-objectmatcher/patch.(*PatchMaker).Calculate\n\t/go/pkg/mod/github.com/cisco-open/k8s-objectmatcher@v1.10.0/patch/patch.go:87\ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.37.0/pkg/reconciler/resource.go:437\ngithub.com/kube-logging/telemetry-controller/controllers/telemetry.(*CollectorReconciler).Reconcile\n\t/usr/local/src/telemetry-controller/controllers/telemetry/collector_controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"}
2025-03-28T00:17:00Z	DEBUG	updating resource	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "collector": "example-collector", "name": "otelcollector-example-collector", "namespace": "collector"}
2025-03-28T00:17:00Z	DEBUG	resource updated	{"controller": "collector", "controllerGroup": "telemetry.kube-logging.dev", "controllerKind": "Collector", "Collector": {"name":"example-collector"}, "namespace": "", "name": "example-collector", "reconcileID": "104acf19-1b42-4491-a494-15f56cb68d9c", "collector": "example-collector", "name": "otelcollector-example-collector", "namespace": "collector"}
Loading...

```

**Comment by csatib02** [comment]
Could you please share step-by-step the way of deploying?

**Comment by samuelarogbonlo** [comment]
@csatib02  i have cluster running on oracle cloud

step 1 installed the controller with helm
```bash
helm upgrade --install --wait --create-namespace --namespace telemetry-controller-system telemetry-controller oci://ghcr.io/kube-logging/helm-charts/telemetry-controller
```

then deployed open serve and telemetry crd with the config i pasted above.

deployed a sample logs generator 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: example-tenant-ns
  labels:
    app: log-generator
    team: iaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
        team: iaas
    spec:
      containers:
      - name: log-generator
        image: busybox:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            # Generate a random log level
            LEVEL=$(( RANDOM % 4 ))
            case $LEVEL in
              0) LVL="DEBUG" ;;
              1) LVL="INFO" ;;
              2) LVL="WARN" ;;
              3) LVL="ERROR" ;;
            esac
            
            # Generate log with timestamp and random message
            echo "$(date -Iseconds) [$LVL] Log message with random number: $RANDOM"
            
            # Generate some JSON formatted logs occasionally
            if [ $(( RANDOM % 10 )) -eq 0 ]; then
              echo "{\"timestamp\":\"$(date -Iseconds)\",\"level\":\"$LVL\",\"message\":\"Structured log entry\",\"count\":$RANDOM,\"service\":\"log-generator\"}"
            fi
            
            # Generate longer log bursts occasionally to simulate application activity
            if [ $(( RANDOM % 30 )) -eq 0 ]; then
              for i in $(seq 1 50); do
                echo "$(date -Iseconds) [$LVL] Batch log $i of 50 with details: user_id=$(( RANDOM % 1000 )), action=request_$i, status_code=$((200 + RANDOM % 5))"
                sleep 0.01
              done
            fi
            
            # Sleep for a short random interval (between 0.1 and 0.5 seconds)
            sleep 0.$(( RANDOM % 5 + 1 ))
          done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator-noshow
  namespace: example-tenant-ns
  labels:
    app: log-generator-noshow
    team: iaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator-noshow
  template:
    metadata:
      labels:
        app: log-generator-noshow
        team: iaas
    spec:
      containers:
      - name: log-generator-noshow
        image: busybox:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            # Generate a random log level
            LEVEL=$(( RANDOM % 4 ))
            case $LEVEL in
              0) LVL="DEBUG" ;;
              1) LVL="INFO" ;;
              2) LVL="WARN" ;;
              3) LVL="ERROR" ;;
            esac
            
            # Generate log with timestamp and random message
            echo "$(date -Iseconds) [$LVL] Log message with random number: $RANDOM"
            
            # Generate some JSON formatted logs occasionally
            if [ $(( RANDOM % 10 )) -eq 0 ]; then
              echo "{\"timestamp\":\"$(date -Iseconds)\",\"level\":\"$LVL\",\"message\":\"Structured log entry\",\"count\":$RANDOM,\"service\":\"log-generator\"}"
            fi
            
            # Generate longer log bursts occasionally to simulate application activity
            if [ $(( RANDOM % 30 )) -eq 0 ]; then
              for i in $(seq 1 50); do
                echo "$(date -Iseconds) [$LVL] Batch log $i of 50 with details: user_id=$(( RANDOM % 1000 )), action=request_$i, status_code=$((200 + RANDOM % 5))"
                sleep 0.01
              done
            fi
            
            # Sleep for a short random interval (between 0.1 and 0.5 seconds)
            sleep 0.$(( RANDOM % 5 + 1 ))
          done

```

it didn't work then i used the helm logs generator provided in the repo 

```bash 
helm install --wait --create-namespace --namespace example-tenant-ns --generate-name oci://ghcr.io/kube-logging/helm-charts/log-generator
```

**Comment by csatib02** [comment]
Did you copy the openobserve token and pasted at the output's `spec.otlp.headers.Authorization` field?
This token gets regenerated on every deploy. There is a guide in our main [README](https://github.com/kube-logging/telemetry-controller/blob/2c4f3ecec9e72e439dc498849ce23b86f67cafd4/README.md?plain=1#L105-L125) you can use.

**Comment by samuelarogbonlo** [comment]
@csatib02 yes i did. if it was a token error should it not be logged in the collector logs like using the open telemetry collector directly would?

**Comment by csatib02** [comment]
Yeah, there should be unauthorized errors showing up. Well then I'm starting to run out of ideas, since the deploy was seamless for me following your step-by-step guide.

**Comment by OverOrion** [comment]
Hey @samuelarogbonlo 

I just went through the steps you have written down and everything worked out of the box, I was able to view logs in openobserve.

I suspect a networking issue in your environment, what k8s distribution (AKS/EKS/minikube/etc) are you using?

**Comment by csatib02** [comment]
@samuelarogbonlo
First of all, thanks for using the project!
I'm going to close this as we were unable to reproduce the issue. If you happened to encounter any problems in the future feel free to reach out.
